# Generated by Django 3.2.3 on 2021-07-12 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='url',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='stories',
            name='time_of_publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 13, 37, 46, 782198), verbose_name='date Published'),
        ),
    ]
